import React from 'react'
import NextHead from 'next/head'

type Props = {
  title: string
}

export default function Head({title}: Props) {
  return (
    <NextHead>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </NextHead>
  )
}
